In [3]:
from datasets import load_dataset
dataset=load_dataset('lukebarousse/data_jobs')

'[Errno 11001] getaddrinfo failed' thrown while requesting HEAD https://huggingface.co/datasets/lukebarousse/data_jobs/resolve/ed776e5a0a8c40ea9d5efbd800772ae52e140f3e/data_jobs.py
Retrying in 1s [Retry 1/5].
Using the latest cached version of the dataset since lukebarousse/data_jobs couldn't be found on the Hugging Face Hub

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\GENIUS DEXTER\\.cache\\huggingface\\datasets\\lukebarousse___data_jobs\\default\\0.0.0\\ed776e5a0a8c40ea9d5efbd800772ae52e140f3e.incomplete\\dataset_info.json'

In [ ]:
dataset['train']

In [ ]:
df=dataset['train'].to_pandas()

In [ ]:
import pandas as pd

#df = pd.read_csv("hf://datasets/lukebarousse/data_jobs/data_jobs.csv")

In [ ]:
data['train']

In [4]:
import pandas as pd
data=pd.read_csv('C:/Users/GENIUS DEXTER/Python For Data Analysis/csv_files/ToyotaCorolla.csv')

data

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23,46986,Diesel,90,1,0,2000,3,1165
1,13750,23,72937,Diesel,90,1,0,2000,3,1165
2,13950,24,41711,Diesel,90,1,0,2000,3,1165
3,14950,26,48000,Diesel,90,0,0,2000,3,1165
4,13750,30,38500,Diesel,90,0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,69,20544,Petrol,86,1,0,1300,3,1025
1432,10845,72,19000,Petrol,86,0,0,1300,3,1015
1433,8500,71,17016,Petrol,86,0,0,1300,3,1015
1434,7250,70,16916,Petrol,86,1,0,1300,3,1015
1435,6950,76,1,Petrol,110,0,0,1600,5,1114

In [5]:
# First n rows, 

data.head(7)

   Price  Age     KM FuelType  HP  MetColor  Automatic    CC  Doors  Weight
0  13500   23  46986   Diesel  90         1          0  2000      3    1165
1  13750   23  72937   Diesel  90         1          0  2000      3    1165
2  13950   24  41711   Diesel  90         1          0  2000      3    1165
3  14950   26  48000   Diesel  90         0          0  2000      3    1165
4  13750   30  38500   Diesel  90         0          0  2000      3    1170
5  12950   32  61000   Diesel  90         0          0  2000      3    1170
6  16900   27  94612   Diesel  90         1          0  2000      3    1245

In [6]:
#by default n=5
data.head()

   Price  Age     KM FuelType  HP  MetColor  Automatic    CC  Doors  Weight
0  13500   23  46986   Diesel  90         1          0  2000      3    1165
1  13750   23  72937   Diesel  90         1          0  2000      3    1165
2  13950   24  41711   Diesel  90         1          0  2000      3    1165
3  14950   26  48000   Diesel  90         0          0  2000      3    1165
4  13750   30  38500   Diesel  90         0          0  2000      3    1170

In [7]:
# Last n rows
data.tail(9)

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
1427,8950,71,29000,Petrol,86,1,1,1300,3,1045
1428,8450,72,26000,Petrol,86,0,0,1300,3,1015
1429,8950,78,24000,Petrol,86,1,1,1300,5,1065
1430,8450,80,23000,Petrol,86,0,0,1300,3,1015
1431,7500,69,20544,Petrol,86,1,0,1300,3,1025
1432,10845,72,19000,Petrol,86,0,0,1300,3,1015
1433,8500,71,17016,Petrol,86,0,0,1300,3,1015
1434,7250,70,16916,Petrol,86,1,0,1300,3,1015
1435,6950,76,1,Petrol,110,0,0,1600,5,1114

In [8]:
# by default n=5
data.tail()

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
1431,7500,69,20544,Petrol,86,1,0,1300,3,1025
1432,10845,72,19000,Petrol,86,0,0,1300,3,1015
1433,8500,71,17016,Petrol,86,0,0,1300,3,1015
1434,7250,70,16916,Petrol,86,1,0,1300,3,1015
1435,6950,76,1,Petrol,110,0,0,1600,5,1114

In [10]:
# data type
type(data)

pandas.core.frame.DataFrame

In [9]:
# Get a column
"""
DataFrame objects are usually stored as dictionaries
"""
data['KM']

0       46986
1       72937
2       41711
3       48000
4       38500
        ...
1431    20544
1432    19000
1433    17016
1434    16916
1435        1
Name: KM, Length: 1436, dtype: int64

In [14]:
# Get a particular line
data.iloc[34:120]

     Price  Age     KM FuelType   HP  MetColor  Automatic    CC  Doors  Weight
34   15500   22  41000   Petrol   97         1          0  1400      3    1100
35   15750   26  43000   Petrol   97         0          0  1400      3    1100
36   15950   25  25000   Petrol   97         0          0  1400      3    1100
37   14950   23  10000   Petrol   97         1          0  1400      3    1100
38   15750   32  25329   Petrol   97         1          0  1400      3    1100
..     ...  ...    ...      ...  ...       ...        ...   ...    ...     ...
115  24990    8   6000   Diesel   90         1          0  2000      5    1280
116  21950    8  10841   Diesel   90         1          0  2000      5    1270
117  17900    7      1   Petrol  110         1          0  1600      3    1105
118  19250   20  63000   Diesel   90         1          0  2000      5    1255
119  22250   17  57313   Diesel  110         1          0  2000      5    1275

[86 rows x 10 columns]

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1436 non-null   int64
 2   KM         1436 non-null   int64
 3   FuelType   1436 non-null   object
 4   HP         1436 non-null   int64
 5   MetColor   1436 non-null   int64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   int64
 9   Weight     1436 non-null   int64
dtypes: int64(9), object(1)
memory usage: 112.3+ KB

In [16]:
len(data)

1436

In [17]:
data.shape

(1436, 10)

In [18]:
data.index

RangeIndex(start=0, stop=1436, step=1)

In [19]:
data.columns

Index(['Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor', 'Automatic', 'CC',
       'Doors', 'Weight'],
      dtype='object')

In [21]:
data.count()

Price        1436
Age          1436
KM           1436
FuelType     1436
HP           1436
MetColor     1436
Automatic    1436
CC           1436
Doors        1436
Weight       1436
dtype: int64

In [26]:
data.describe()

,Price,Age,KM,HP,MetColor,Automatic,CC,Doors,Weight
count,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.00000
mean,10730.824513,55.947075,68533.259749,101.502089,0.674791,0.055710,1566.827994,4.033426,1072.45961
std,3626.964585,18.599988,37506.448872,14.981080,0.468616,0.229441,187.182436,0.952677,52.64112
min,4350.000000,1.000000,1.000000,69.000000,0.000000,0.000000,1300.000000,2.000000,1000.00000
25%,8450.000000,44.000000,43000.000000,90.000000,0.000000,0.000000,1400.000000,3.000000,1040.00000
50%,9900.000000,61.000000,63389.500000,110.000000,1.000000,0.000000,1600.000000,4.000000,1070.00000
75%,11950.000000,70.000000,87020.750000,110.000000,1.000000,0.000000,1600.000000,5.000000,1085.00000
max,32500.000000,80.000000,243000.000000,192.000000,1.000000,1.000000,2000.000000,5.000000,1615.00000

In [30]:
data.Price.unique()

array([13500, 13750, 13950, 14950, 12950, 16900, 18600, 21500, 20950,
       19950, 19600, 22500, 22000, 22750, 17950, 16750, 16950, 15950,
       16250, 17495, 15750, 15500, 14750, 19000, 15800, 21950, 20500,
       13250, 15250, 18950, 15999, 16500, 18750, 22250, 12995, 18450,
       16895, 14900, 17250, 15450, 16650, 17450, 16450, 18900, 18990,
       18500, 19450, 18800, 32500, 31000, 31275, 24950, 22950, 24990,
       17900, 19250, 16350, 21750, 15850, 23000, 19900, 23950, 24500,
       17200, 19500, 16868, 19750, 20750, 17650, 17795, 18245, 23750,
       18700, 21125,  6950,  9500, 11950,  7750,  4350,  4750, 11750,
       11900,  9950, 11495, 11250, 10500, 10450, 11500, 12500, 10950,
       11450, 11790, 12450, 11690, 12750, 11925, 12900, 11650, 10850,
        9940, 13450, 12495, 12000, 11480, 14990, 12850, 11700, 11895,
       13875, 12295, 13995,  9900, 11990, 10750, 11695, 11000, 12400,
       12200, 12695, 14350, 10250,  6500,  6400,  7000,  8900,  8500,
        8950,  9250,  9450,  8250,  4450,  9000,  5150,  7900, 10900,
        9750, 11290, 10895, 10995,  9850,  8695, 10990,  8750,  9930,
        9799,  9700,  9990,  9475, 10000, 10495,  9400,  9650,  9550,
       13000, 11710,  9980, 12250, 11930, 10800, 10600,  7500,  5950,
        6900,  5751,  7950,  6250,  8450,  7350,  9800,  7995,  8600,
        7250,  8000,  8495,  9895,  7999,  8490,  8150,  7450,  9130,
        8990,  8995,  9995, 10400,  8800,  7800,  8100,  8200, 10295,
        9795, 10350,  8400,  8895,  9390,  8745,  8850,  9695,  9245,
        5900,  6000,  5250,  4400,  6750,  6150,  5750,  5800,  5740,
        6550,  6450,  5600,  6650,  7600,  7460,  6800,  8700,  6640,
        8050,  7795,  6490,  6425,  6495,  6990,  7200,  7300,  9200,
        7850,  7495,  7990,  7490,  7145,  7400,  6999,  7499,  7150,
        5845, 10845])

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1436 non-null   int64
 2   KM         1436 non-null   int64
 3   FuelType   1436 non-null   object
 4   HP         1436 non-null   int64
 5   MetColor   1436 non-null   int64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   int64
 9   Weight     1436 non-null   int64
dtypes: int64(9), object(1)
memory usage: 112.3+ KB

In [34]:
data[(data.KM>40000) & (data.Weight>1200)]

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
6,16900,27,94612,Diesel,90,1,0,2000,3,1245
7,18600,30,75889,Diesel,90,1,0,2000,3,1245
43,16950,27,110404,Diesel,90,0,0,2000,5,1255
44,16950,22,100250,Diesel,90,0,0,2000,5,1255
45,19000,23,84000,Diesel,90,0,0,2000,5,1270
46,17950,27,79375,Diesel,90,1,0,2000,5,1255
48,17950,22,72215,Diesel,90,1,0,2000,5,1255
50,17950,22,62636,Diesel,90,1,0,2000,5,1255
87,17950,20,66966,Diesel,90,1,0,2000,3,1245
89,21950,19,50005,Diesel,110,1,0,2000,3,1265
118,19250,20,63000,Diesel,90,1,0,2000,5,1255
119,22250,17,57313,Diesel,110,1,0,2000,5,1275
121,19950,19,51099,Diesel,90,1,0,2000,5,1255
188,11950,40,179860,Diesel,90,1,0,2000,5,1205
197,14750,39,108847,Diesel,90,1,0,2000,5,1205
211,14750,40,80425,Diesel,90,1,0,2000,5,1205
221,12450,44,74172,Petrol,110,1,0,1600,5,1615
268,14750,40,48952,Diesel,90,1,0,2000,5,1205
654,6950,65,114383,Diesel,90,0,0,2000,3,1260
960,9390,66,50806,Petrol,86,0,0,1300,3,1480